# Generated by Django 4.2.26 on 2025-11-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(max_length=5)),
                ('numero_quarto', models.IntegerField(default=1)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bairro', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=5)),
                ('descricao', models.CharField(max_length=250)),
                ('categoria', models.CharField(choices=[('APARTAMENTO', 'Apartamento'), ('CASA', 'Casa'), ('PONTO COMERCIAL', 'Ponto Comercial')], default='', max_length=100)),
            ],
        ),
    ]
