# Generated by Django 4.2.26 on 2025-11-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imobiliaria', '0002_imovel_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='publicada',
            field=models.BooleanField(default=True),
        ),
    ]
