# Generated by Django 5.2.8 on 2025-11-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imobiliaria", "0003_imovel_publicada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imovel",
            name="tamanho",
            field=models.IntegerField(),
        ),
    ]
