# Generated by Django 5.2.8 on 2025-11-27 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imobiliaria", "0004_alter_imovel_tamanho"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImagemImovel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.ImageField(upload_to="fotos_extras/%Y/%m/%d/")),
                (
                    "imovel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens",
                        to="imobiliaria.imovel",
                    ),
                ),
            ],
        ),
    ]
